Repository woowa-techcamp-2021/deal-6, pull requests merged in 2021-07, with the labels that each got.

#3 README.md, .gitignore 수정
  .gitignore
  README.md
Labels: documentation

#28 express 폴더 구조화
  .gitignore
  README.md
  server/app.js
  server/constants/README.md
  server/middlewares/README.md
  server/package.json
  server/routes/README.md
  server/services/README.md
Labels: be, env

#29 동작하는 express 서버 제작
  server/app.js
  server/package-lock.json
  server/package.json
Labels: be, env

#30 gitignore 에 pem 추가
  .gitignore
  server/app.js
  server/constants/README.md
  server/middlewares/README.md
  server/package-lock.json
  server/package.json
  server/routes/README.md
  server/services/README.md
Labels: Common, be

#36 [#32] webpack, babel 설정
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/webpack.config.js
  server/package.json
Labels: env, fe

#38 utils, repository 폴더 추가
  server/repository/README.md
  server/utils/README.md
Labels: be, env

#40 5개의 페이지별 라우터 제작
  server/middlewares/auth.js
  server/routes/README.md
  server/routes/detail-router.js
  server/routes/main-router.js
  server/routes/my-town-router.js
  server/routes/post-router.js
  server/routes/user-router.js
Labels: be

#41 프론트엔드 구조 설정
  client/.eslintrc.json
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/apis/Readme.md
  client/src/components/base/Readme.md
  client/src/components/base/product-lists/product-lists.css
  client/src/components/base/product-lists/product-lists.js
  client/src/components/base/product-lists/product/product.js
  client/src/components/main-page/navbar/navbar.js
  client/src/index.css
  client/src/index.js
  client/src/pages/1page/1page.js
  client/src/pages/1page/1page__inner/page__inner.js
  client/src/pages/2page/2page.js
  client/src/pages/Readme.md
  client/src/pages/main-page.js
  client/src/reset.css
  client/src/router.js
  client/src/styles/index.css
  client/src/util/Readme.md
Labels: env, fe

#43 이미지 파일 추가 & 유틸 생성
  client/assets/imgs/account.svg
  client/assets/imgs/add.svg
  client/assets/imgs/arrow_back.svg
  client/assets/imgs/arrow_forward.svg
  client/assets/imgs/cancel.svg
  client/assets/imgs/category.svg
  client/assets/imgs/chat_bubble_mini.svg
  client/assets/imgs/done.svg
  client/assets/imgs/exit.svg
  client/assets/imgs/expand_more.svg
  client/assets/imgs/favorite.svg
  client/assets/imgs/favorite_border.svg
  client/assets/imgs/favorite_border_mini.svg
  client/assets/imgs/image.svg
  client/assets/imgs/location.svg
  client/assets/imgs/menu.svg
  client/assets/imgs/more_vert.svg
  client/assets/imgs/send.svg
  client/src/components/base/product-lists/product-lists.js
  client/src/components/main-page/navbar/navbar.js
  client/src/constants/icon-path.js
  client/src/util/createDOMwithSelector.js
Labels: fe

#44 Mainpage 구현
  client/index.html
  client/src/components/base/product-lists/product-lists.css
  client/src/components/base/product-lists/product-lists.js
  client/src/components/main-page/navbar/navbar.css
  client/src/components/main-page/navbar/navbar.js
  client/src/constants/icon-path.js
  client/src/index.css
Labels: fe

#45 mainpage UI 구현
  client/assets/imgs/account.svg
  client/assets/imgs/add.svg
  client/assets/imgs/arrow_back.svg
  client/assets/imgs/arrow_forward.svg
  client/assets/imgs/cancel.svg
  client/assets/imgs/category.svg
  client/assets/imgs/chat_bubble_mini.svg
  client/assets/imgs/done.svg
  client/assets/imgs/exit.svg
  client/assets/imgs/expand_more.svg
  client/assets/imgs/favorite.svg
  client/assets/imgs/favorite_border.svg
  client/assets/imgs/favorite_border_mini.svg
  client/assets/imgs/image.svg
  client/assets/imgs/location.svg
  client/assets/imgs/menu.svg
  client/assets/imgs/more_vert.svg
  client/assets/imgs/photo.jpeg
  client/assets/imgs/send.svg
  client/src/components/base/product-lists/product-lists.css
  client/src/components/base/product-lists/product-lists.js
  client/src/components/main-page/navbar/navbar.css
  client/src/components/main-page/navbar/navbar.js
  client/src/index.css
  client/src/index.js
  server/app.js
Labels: be, fe

#46 상품상세페이지 데모데이를 위한 중간 커밋
  client/assets/icons/account.svg
  client/assets/icons/add.svg
  client/assets/icons/arrow_back.svg
  client/assets/icons/arrow_forward.svg
  client/assets/icons/cancel.svg
  client/assets/icons/category.svg
  client/assets/icons/chat_bubble_mini.svg
  client/assets/icons/done.svg
  client/assets/icons/exit.svg
  client/assets/icons/expand_more.svg
  client/assets/icons/favorite.svg
  client/assets/icons/favorite_border.svg
  client/assets/icons/favorite_border_mini.svg
  client/assets/icons/image.svg
  client/assets/icons/location.svg
  client/assets/icons/menu.svg
  client/assets/icons/more_vert.svg
  client/assets/icons/send.svg
  client/assets/imgs/shoes-1.jpg
  client/src/components/base/product-lists/product-lists.js
  client/src/components/base/product-lists/product/product.js
  client/src/components/detail-page/footer/footer.css
  client/src/components/detail-page/footer/footer.js
  client/src/components/detail-page/navigator/navigator.css
  client/src/components/detail-page/navigator/navigator.js
  client/src/components/detail-page/section/img-container/img-container.css
  client/src/components/detail-page/section/img-container/img-container.js
  client/src/components/detail-page/section/info-container/info-container.css
  client/src/components/detail-page/section/info-container/info-container.js
  client/src/components/detail-page/section/section.css
  client/src/components/detail-page/section/section.js
  client/src/components/main-page/navbar/navbar.js
  client/src/constants/icon-path.js
  client/src/index.css
  client/src/pages/detail-page.css
  client/src/pages/detail-page.js
  client/src/router.js
  client/src/util/createDOMwithSelector.js
  client/webpack.config.js
Labels: fe

#48 회원가입 페이지 구현 및 메인페이지 수정
  client/assets/icons/arrow_back_black.svg
  client/assets/icons/exit.svg
  client/assets/icons/favorite.svg
  client/src/components/base/Readme.md
  client/src/components/base/large-button/large-button.css
  client/src/components/base/large-button/large-button.js
  client/src/components/base/navigator/navigator.css
  client/src/components/base/navigator/navigator.js
  client/src/components/base/product-lists/product-lists.css
  client/src/components/base/product-lists/product-lists.js
  client/src/components/main-page/navbar/navbar.js
  client/src/components/main-page/write-post-button/write-post-button.js
  client/src/components/signup-page/body/body.css
  client/src/components/signup-page/body/body.js
  client/src/index.css
  client/src/pages/main-page.js
  client/src/pages/signup-page.js
  client/src/router.js
Labels: fe

#51 Menupage 구현 및 PR 리팩토링 반영
  client/src/components/base/chat-list/chat-list.css
  client/src/components/base/chat-list/chat-list.js
  client/src/components/base/large-button/large-button.js
  client/src/components/base/navigation-bar/navigation-bar.css
  client/src/components/base/navigation-bar/navigation-bar.js
  client/src/components/base/product-list/product-list.css
  client/src/components/base/product-list/product-list.js
  client/src/components/location-page/body/body.js
  client/src/components/main-page/navigation-bar/navigation-bar.css
  client/src/components/main-page/navigation-bar/navigation-bar.js
  client/src/components/menu-page/main-navigation-bar/main-navigation-bar.css
  client/src/components/menu-page/main-navigation-bar/main-navigation-bar.js
  client/src/components/signup-page/body/body.js
  client/src/index.css
  client/src/pages/location-page.js
  client/src/pages/main-page.js
  client/src/pages/menu-page.js
  client/src/pages/signup-page.js
  client/src/router.js
Labels: fe

#53 상세페이지 구현
  client/src/components/detail-page/footer/footer.css
  client/src/components/detail-page/footer/footer.js
  client/src/components/detail-page/navigator/navigator.css
  client/src/components/detail-page/section/img-container/img-container.css
  client/src/components/detail-page/section/img-container/img-container.js
  client/src/components/detail-page/section/info-container/info-container.css
  client/src/components/detail-page/section/info-container/info-container.js
  client/src/components/detail-page/section/section.css
  client/src/components/detail-page/section/section.js
  client/src/components/detail-page/tool-bar/tool-bar.css
  client/src/components/detail-page/tool-bar/tool-bar.js
  client/src/index.css
  client/src/pages/detail-page.css
  client/src/pages/detail-page.js
  client/src/util/selectorHandler.js
Labels: fe

#59 [#8, #15] detail-page 및 user-page 파일경로 수정
  client/src/pages/detail-page.js
  client/src/pages/user-page.js
Labels: fe

#62 userpage 애니메이션 구현!
  client/src/components/base/alert/alert.js
  client/src/components/base/navigation-bar/navigation-bar.js
  client/src/components/location-page/location-modal/location-modal.css
  client/src/components/location-page/location-modal/location-modal.js
  client/src/components/main-page/category/body/body.css
  client/src/components/main-page/category/body/body.js
  client/src/components/main-page/category/category.css
  client/src/components/main-page/category/category.js
  client/src/components/main-page/navigation-bar/navigation-bar.js
  client/src/pages/location-page.js
  client/src/pages/main-page.js
  client/src/pages/menu-page.css
  client/src/pages/menu-page.js
  client/src/pages/user-page.css
  client/src/pages/user-page.js
  client/src/router.js
Labels: fe

#64 sign up 기능 구현까지 끄--읕
  client/assets/icons/loading-loader-svgrepo-com.svg
  client/src/components/base/large-button/large-button.css
  client/src/components/base/large-button/large-button.js
  client/src/components/base/product-list/product-list.css
  client/src/components/base/product-list/product-list.js
  client/src/components/main-page/category/category.css
  client/src/components/main-page/location-mini-modal/location-mini-modal.css
  client/src/components/main-page/location-mini-modal/location-mini-modal.js
  client/src/components/main-page/navigation-bar/navigation-bar.js
  client/src/components/signup-page/body/body.css
  client/src/components/signup-page/body/body.js
  client/src/components/signup-page/modal/modal.css
  client/src/components/signup-page/modal/modal.js
  client/src/components/user-page/section/section.css
  client/src/components/writing-page/body/body.css
  client/src/components/writing-page/body/body.js
  client/src/index.css
  client/src/pages/main-page.js
  client/src/pages/user-page.js
Labels: fe

#72 Express server 와 DB 연결
  server/config/config-sample.js
  server/db/db.js
Labels: be, env

#65 계정페이지 구현 끄--읕
  client/src/components/base/large-button/large-button.js
  client/src/components/base/navigation-bar/navigation-bar.js
  client/src/components/main-page/category/body/body.js
  client/src/components/user-page/section/section.css
  client/src/components/user-page/section/section.js
  client/src/pages/user-page.js
Labels: fe

#73 JWT Token 관련 제작
  server/middlewares/auth.js
  server/middlewares/decode-jwt.js
  server/routes/detail-router.js
  server/routes/main-router.js
  server/routes/my-location-router.js
  server/routes/my-town-router.js
  server/routes/post-router.js
  server/routes/user-router.js
  server/utils/jwt.js
Labels: be

#76 서버 계정페이지 API 구현
  server/constants/error.js
  server/constants/success.js
  server/middlewares/decode-jwt.js
  server/middlewares/error-handler.js
  server/repository/location-repository.js
  server/repository/user-repository.js
  server/services/user-service.js
  server/utils/jwt.js
  server/utils/queryExecutor.js
Labels: be
